### ISSUE TITLE
Rename the master branch of this repo

### ISSUE THREAD

**Issue by hober** [w3c/idcg#4]
It's really easy to do.

```sh
git branch -m master main
git push -u origin main
```

See [these more detailed instructions](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx) for more.

**Comment by LJWatson** [comment]
Done. I think. I used the above commands, but when I checked in the Github repo it didn't seem to have taken, so I switched the base branch to main there too. Hopefully it's done the trick.
